#!/bin/bash

# install boot loaders
spawn_chroot "DEBIAN_FRONTEND=noninteractive apt-get -y install extlinux grub-efi-amd64"

# fetch and install kernel via ubuntu ppa
mkdir -p /mnt/baremetal/root/kernel-5.10.9
cd /mnt/baremetal/root/kernel-5.10.9

wget https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.9/amd64/linux-headers-5.10.9-051009-generic_5.10.9-051009.202101191835_amd64.deb
wget https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.9/amd64/linux-headers-5.10.9-051009_5.10.9-051009.202101191835_all.deb
wget https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.9/amd64/linux-image-unsigned-5.10.9-051009-generic_5.10.9-051009.202101191835_amd64.deb
wget https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.9/amd64/linux-modules-5.10.9-051009-generic_5.10.9-051009.202101191835_amd64.deb
spawn_chroot "dpkg -i /root/kernel-5.10.9/*.deb"
